### ISSUE TITLE
CreateTimeTable- Holiday button doesnt work

### ISSUE THREAD

**Issue by Juice234** [CianMcGriskin/Prof-IT-Project#5]
In the holiday timetable the holiday button sets the hours to 0 but in the DB it prints it as 24 hours worked.

**Comment by CianMcGriskin** [comment]
I fixed it so that in the regular employee view timetable shows day off and 0 hours worked, in terms of calculating employee pay we could work on totaling the hours from the view point through the HTML, as for changing the hours in the db, not sure if that is possible with the way the information is set up
